// Code generated by rpc_gen.go. DO NOT EDIT.
//
// This file contains auto-generated LSP RPC method implementations.
// These methods follow a consistent pattern: create context with timeout,
// call the LSP method with params, parse the result.
//
// To regenerate after editing templates:
// 1. Edit the method templates below
// 2. Run: go generate ./internal/lsp/generate

package lsp

import (
	"context"
	"encoding/json"
	"fmt"
	"time"
)

// Completion requests completion items at the given position.
func (c *Client) Completion(uri string, line, character int) ([]CompletionItem, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	position, err := c.internalPositionToProtocol(uri, Position{Line: line, Character: character})
	if err != nil {
		return nil, fmt.Errorf("completion position: %w", err)
	}

	result, err := c.call(ctx, "textDocument/completion", map[string]any{
		"textDocument": map[string]any{"uri": uri},
		"position":     map[string]any{"line": position.Line, "character": position.Character},
	})
	if err != nil {
		return nil, err
	}

	var items []CompletionItem
	var list struct {
		Items []struct {
			Label      string `json:"label"`
			Detail     string `json:"detail"`
			InsertText string `json:"insertText"`
			Kind       int    `json:"kind"`
		} `json:"items"`
	}
	if err := json.Unmarshal(result, &list); err == nil && len(list.Items) > 0 {
		for _, item := range list.Items {
			insertText := item.InsertText
			if insertText == "" {
				insertText = item.Label
			}
			items = append(items, CompletionItem{
				Label:      item.Label,
				Detail:     item.Detail,
				InsertText: insertText,
				Kind:       item.Kind,
			})
		}
		return items, nil
	}
	var plainItems []struct {
		Label      string `json:"label"`
		Detail     string `json:"detail"`
		InsertText string `json:"insertText"`
		Kind       int    `json:"kind"`
	}
	if err := json.Unmarshal(result, &plainItems); err == nil {
		for _, item := range plainItems {
			insertText := item.InsertText
			if insertText == "" {
				insertText = item.Label
			}
			items = append(items, CompletionItem{
				Label:      item.Label,
				Detail:     item.Detail,
				InsertText: insertText,
				Kind:       item.Kind,
			})
		}
	}
	return items, nil
}

// Hover requests hover info at the given position.
func (c *Client) Hover(uri string, line, character int) (*HoverResult, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	position, err := c.internalPositionToProtocol(uri, Position{Line: line, Character: character})
	if err != nil {
		return nil, fmt.Errorf("hover position: %w", err)
	}

	result, err := c.call(ctx, "textDocument/hover", map[string]any{
		"textDocument": map[string]any{"uri": uri},
		"position":     map[string]any{"line": position.Line, "character": position.Character},
	})
	if err != nil {
		return nil, err
	}

	if string(result) == "null" {
		return nil, nil
	}

	var hover struct {
		Contents any `json:"contents"`
	}
	if err := json.Unmarshal(result, &hover); err != nil {
		return nil, err
	}

	content := extractHoverContent(hover.Contents)
	if content == "" {
		return nil, nil
	}

	return &HoverResult{Content: content}, nil
}

// Definition requests go-to-definition at the given position.
func (c *Client) Definition(uri string, line, character int) ([]Location, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	position, err := c.internalPositionToProtocol(uri, Position{Line: line, Character: character})
	if err != nil {
		return nil, fmt.Errorf("definition position: %w", err)
	}

	result, err := c.call(ctx, "textDocument/definition", map[string]any{
		"textDocument": map[string]any{"uri": uri},
		"position":     map[string]any{"line": position.Line, "character": position.Character},
	})
	if err != nil {
		return nil, err
	}

	if string(result) == "null" {
		return nil, nil
	}

	var locations []Location
	var locs []struct {
		URI   string `json:"uri"`
		Range struct {
			Start struct {
				Line      int `json:"line"`
				Character int `json:"character"`
			} `json:"start"`
			End struct {
				Line      int `json:"line"`
				Character int `json:"character"`
			} `json:"end"`
		} `json:"range"`
	}
	if err := json.Unmarshal(result, &locs); err == nil {
		for _, loc := range locs {
			locations = append(locations, Location{
				URI:       loc.URI,
				StartLine: loc.Range.Start.Line,
				StartCol:  loc.Range.Start.Character,
				EndLine:   loc.Range.End.Line,
				EndCol:    loc.Range.End.Character,
			})
		}
		return c.locationsFromProtocol(locations)
	}
	var single struct {
		URI   string `json:"uri"`
		Range struct {
			Start struct {
				Line      int `json:"line"`
				Character int `json:"character"`
			} `json:"start"`
			End struct {
				Line      int `json:"line"`
				Character int `json:"character"`
			} `json:"end"`
		} `json:"range"`
	}
	if err := json.Unmarshal(result, &single); err == nil && single.URI != "" {
		locations = append(locations, Location{
			URI:       single.URI,
			StartLine: single.Range.Start.Line,
			StartCol:  single.Range.Start.Character,
			EndLine:   single.Range.End.Line,
			EndCol:    single.Range.End.Character,
		})
	}
	return c.locationsFromProtocol(locations)
}

// References requests find-references at the given position.
func (c *Client) References(uri string, line, character int) ([]Location, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	position, err := c.internalPositionToProtocol(uri, Position{Line: line, Character: character})
	if err != nil {
		return nil, fmt.Errorf("references position: %w", err)
	}

	result, err := c.call(ctx, "textDocument/references", map[string]any{
		"textDocument": map[string]any{"uri": uri},
		"position":     map[string]any{"line": position.Line, "character": position.Character},
		"context":      map[string]any{"includeDeclaration": true},
	})
	if err != nil {
		return nil, err
	}

	if string(result) == "null" {
		return nil, nil
	}

	var locations []Location
	var locs []struct {
		URI   string `json:"uri"`
		Range struct {
			Start struct {
				Line      int `json:"line"`
				Character int `json:"character"`
			} `json:"start"`
			End struct {
				Line      int `json:"line"`
				Character int `json:"character"`
			} `json:"end"`
		} `json:"range"`
	}
	if err := json.Unmarshal(result, &locs); err == nil {
		for _, loc := range locs {
			locations = append(locations, Location{
				URI:       loc.URI,
				StartLine: loc.Range.Start.Line,
				StartCol:  loc.Range.Start.Character,
				EndLine:   loc.Range.End.Line,
				EndCol:    loc.Range.End.Character,
			})
		}
	}
	return c.locationsFromProtocol(locations)
}

// Rename requests rename at the given position.
func (c *Client) Rename(uri string, line, character int, newName string) (WorkspaceEdit, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	position, err := c.internalPositionToProtocol(uri, Position{Line: line, Character: character})
	if err != nil {
		return WorkspaceEdit{}, fmt.Errorf("rename position: %w", err)
	}

	result, err := c.call(ctx, "textDocument/rename", map[string]any{
		"textDocument": map[string]any{"uri": uri},
		"position":     map[string]any{"line": position.Line, "character": position.Character},
		"newName":      newName,
	})
	if err != nil {
		return WorkspaceEdit{}, err
	}

	if string(result) == "null" {
		return WorkspaceEdit{}, nil
	}

	var edit WorkspaceEdit
	if err := json.Unmarshal(result, &edit); err != nil {
		return WorkspaceEdit{}, err
	}
	converted, err := c.workspaceEditFromProtocol(edit)
	if err != nil {
		return WorkspaceEdit{}, err
	}
	return converted, nil
}

// SignatureHelp requests signature help at the given position.
func (c *Client) SignatureHelp(uri string, line, character int) (*SignatureHelp, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()
	position, err := c.internalPositionToProtocol(uri, Position{Line: line, Character: character})
	if err != nil {
		return nil, fmt.Errorf("signature help position: %w", err)
	}

	result, err := c.call(ctx, "textDocument/signatureHelp", map[string]any{
		"textDocument": map[string]any{"uri": uri},
		"position":     map[string]any{"line": position.Line, "character": position.Character},
	})
	if err != nil {
		return nil, err
	}

	if string(result) == "null" {
		return nil, nil
	}

	var help SignatureHelp
	if err := json.Unmarshal(result, &help); err != nil {
		return nil, err
	}
	return &help, nil
}

// Formatting requests formatting for a document.
func (c *Client) Formatting(uri string, options FormattingOptions) ([]TextEdit, error) {
	if !c.SupportsFormatting() {
		return nil, nil
	}

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	result, err := c.call(ctx, "textDocument/formatting", formattingRequestParams(uri, options))
	if err != nil {
		return nil, err
	}

	if string(result) == "null" {
		return nil, nil
	}

	var edits []struct {
		Range struct {
			Start struct {
				Line      int `json:"line"`
				Character int `json:"character"`
			} `json:"start"`
			End struct {
				Line      int `json:"line"`
				Character int `json:"character"`
			} `json:"end"`
		} `json:"range"`
		NewText string `json:"newText"`
	}
	if err := json.Unmarshal(result, &edits); err != nil {
		return nil, err
	}
	var textEdits []TextEdit
	for _, edit := range edits {
		textEdits = append(textEdits, TextEdit{
			StartLine: edit.Range.Start.Line,
			StartCol:  edit.Range.Start.Character,
			EndLine:   edit.Range.End.Line,
			EndCol:    edit.Range.End.Character,
			NewText:   edit.NewText,
		})
	}
	converted, err := c.textEditsFromProtocol(uri, textEdits)
	if err != nil {
		return nil, err
	}
	return converted, nil
}

// FoldingRange requests folding ranges for a document.
func (c *Client) FoldingRange(uri string) ([]FoldingRange, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	result, err := c.call(ctx, "textDocument/foldingRange", map[string]any{
		"textDocument": map[string]any{"uri": uri},
	})
	if err != nil {
		return nil, err
	}

	if string(result) == "null" {
		return nil, nil
	}

	var ranges []FoldingRange
	if err := json.Unmarshal(result, &ranges); err != nil {
		return nil, err
	}
	converted, err := c.foldingRangesFromProtocol(uri, ranges)
	if err != nil {
		return nil, err
	}
	return converted, nil
}

// CodeAction requests code actions for the given range.
func (c *Client) CodeAction(uri string, startLine, startCol, endLine, endCol int, diagnostics []Diagnostic) ([]CodeAction, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	rangeValue, err := c.internalRangeToProtocol(uri, Range{
		Start: Position{Line: startLine, Character: startCol},
		End:   Position{Line: endLine, Character: endCol},
	})
	if err != nil {
		return nil, fmt.Errorf("code action range: %w", err)
	}
	protocolDiagnostics, err := c.diagnosticsToProtocol(uri, diagnostics)
	if err != nil {
		return nil, fmt.Errorf("code action diagnostics: %w", err)
	}

	result, err := c.call(ctx, "textDocument/codeAction", map[string]any{
		"textDocument": map[string]any{"uri": uri},
		"range": map[string]any{
			"start": map[string]any{"line": rangeValue.Start.Line, "character": rangeValue.Start.Character},
			"end":   map[string]any{"line": rangeValue.End.Line, "character": rangeValue.End.Character},
		},
		"context": map[string]any{"diagnostics": protocolDiagnostics},
	})
	if err != nil {
		return nil, err
	}

	if string(result) == "null" {
		return nil, nil
	}

	var actions []CodeAction
	if err := json.Unmarshal(result, &actions); err != nil {
		return nil, err
	}
	converted, err := c.codeActionsFromProtocol(uri, actions)
	if err != nil {
		return nil, err
	}
	return converted, nil
}

// DocumentSymbol requests document symbols for a document.
func (c *Client) DocumentSymbol(uri string) ([]DocumentSymbol, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	result, err := c.call(ctx, "textDocument/documentSymbol", map[string]any{
		"textDocument": map[string]any{"uri": uri},
	})
	if err != nil {
		return nil, err
	}

	if string(result) == "null" {
		return nil, nil
	}

	var symbols []DocumentSymbol
	if err := json.Unmarshal(result, &symbols); err != nil {
		return nil, err
	}
	converted, err := c.documentSymbolsFromProtocol(uri, symbols)
	if err != nil {
		return nil, err
	}
	return converted, nil
}
