// Code generated by teak - DO NOT EDIT
// Tests for viewport_cache_wip.go
// These tests validate the ViewportCache implementation.
// The cache is not yet integrated into the render loop (Phase 3).

package editor

import (
	"testing"

	"teak/internal/text"
	"teak/internal/ui"
)

func TestViewportCache(t *testing.T) {
	theme := ui.NordTheme()
	cache := NewViewportCache(24)
	buf := text.NewBufferFromBytes([]byte("test content\nline 2\nline 3"))
	v := Viewport{ScrollY: 0, Width: 80, Height: 24}

	// Initially invalid
	if cache.IsValid(buf, &v, nil, theme) {
		t.Error("Cache should be invalid initially")
	}

	// Update state
	cache.UpdateState(buf, &v, nil, theme)

	// Now valid
	if !cache.IsValid(buf, &v, nil, theme) {
		t.Error("Cache should be valid after update")
	}

	// Invalidate on scroll
	v.ScrollY = 10
	if cache.IsValid(buf, &v, nil, theme) {
		t.Error("Cache should be invalid after scroll")
	}

	// Reset and test buffer version change
	v.ScrollY = 0
	cache.UpdateState(buf, &v, nil, theme)
	if !cache.IsValid(buf, &v, nil, theme) {
		t.Error("Cache should be valid")
	}

	// Modify buffer (this increments version)
	buf.InsertAtCursor([]byte("x"))
	if cache.IsValid(buf, &v, nil, theme) {
		t.Error("Cache should be invalid after buffer modification")
	}
}

func TestViewportCacheSelection(t *testing.T) {
	theme := ui.NordTheme()
	cache := NewViewportCache(24)
	buf := text.NewBufferFromBytes([]byte("line 1\nline 2\nline 3"))
	v := Viewport{ScrollY: 0, Width: 80, Height: 24}

	// Update with no selection
	cache.UpdateState(buf, &v, nil, theme)
	if !cache.IsValid(buf, &v, nil, theme) {
		t.Error("Cache should be valid with no selection")
	}

	// Create selection
	sel := &text.Selection{
		Anchor: text.Position{Line: 0, Col: 0},
		Head:   text.Position{Line: 1, Col: 5},
	}
	if cache.IsValid(buf, &v, sel, theme) {
		t.Error("Cache should be invalid after selection created")
	}

	// Update with selection
	cache.UpdateState(buf, &v, sel, theme)
	if !cache.IsValid(buf, &v, sel, theme) {
		t.Error("Cache should be valid with selection")
	}

	// Change selection
	sel2 := &text.Selection{
		Anchor: text.Position{Line: 1, Col: 0},
		Head:   text.Position{Line: 2, Col: 5},
	}
	if cache.IsValid(buf, &v, sel2, theme) {
		t.Error("Cache should be invalid after selection changed")
	}
}

func TestViewportCacheGetSet(t *testing.T) {
	cache := NewViewportCache(24)

	// Get from empty cache
	content, ok := cache.Get(0)
	if ok || content != "" {
		t.Error("Get from empty cache should return false")
	}

	// Set a value
	cache.Set(0, 5, "rendered line content")

	// Get the value
	content, ok = cache.Get(0)
	if !ok || content != "rendered line content" {
		t.Error("Get should return cached content")
	}

	// Get wrong row
	content, ok = cache.Get(1)
	if ok {
		t.Error("Get for unset row should return false")
	}

	// Get out of bounds
	content, ok = cache.Get(100)
	if ok {
		t.Error("Get out of bounds should return false")
	}
}

func TestViewportCacheInvalidateLine(t *testing.T) {
	cache := NewViewportCache(24)

	// Set multiple lines
	cache.Set(0, 0, "line 0")
	cache.Set(1, 1, "line 1")
	cache.Set(2, 2, "line 2")

	// Verify all cached
	for i := 0; i < 3; i++ {
		if _, ok := cache.Get(i); !ok {
			t.Errorf("Line %d should be cached", i)
		}
	}

	// Invalidate line 1
	cache.InvalidateLine(1)

	// Verify line 1 invalidated, others still valid
	if _, ok := cache.Get(0); !ok {
		t.Error("Line 0 should still be cached")
	}
	if _, ok := cache.Get(1); ok {
		t.Error("Line 1 should be invalidated")
	}
	if _, ok := cache.Get(2); !ok {
		t.Error("Line 2 should still be cached")
	}
}

func TestViewportCacheInvalidateAll(t *testing.T) {
	cache := NewViewportCache(24)

	// Set multiple lines
	cache.Set(0, 0, "line 0")
	cache.Set(1, 1, "line 1")
	cache.Set(2, 2, "line 2")

	// Invalidate all
	cache.InvalidateAll()

	// Verify all invalidated
	for i := 0; i < 3; i++ {
		if _, ok := cache.Get(i); ok {
			t.Errorf("Line %d should be invalidated", i)
		}
	}
}

func TestViewportCacheResize(t *testing.T) {
	cache := NewViewportCache(24)

	// Set values at various rows
	cache.Set(0, 0, "line 0")
	cache.Set(10, 10, "line 10")
	cache.Set(23, 23, "line 23")

	// Shrink cache
	cache.Resize(12)

	// Verify accessible rows are preserved
	if _, ok := cache.Get(0); !ok {
		t.Error("Row 0 should still be cached after shrink")
	}
	if _, ok := cache.Get(10); !ok {
		t.Error("Row 10 should still be cached after shrink")
	}

	// Verify out-of-bounds access returns false
	if _, ok := cache.Get(23); ok {
		t.Error("Row 23 should be out of bounds after shrink")
	}

	// Grow cache back
	cache.Resize(24)

	// Verify original values still there (within new bounds)
	if _, ok := cache.Get(0); !ok {
		t.Error("Row 0 should be cached after grow")
	}
}

func TestComputeSelectionHash(t *testing.T) {
	// Empty selection
	if hash := computeSelectionHash(nil); hash != 0 {
		t.Errorf("Empty selection hash should be 0, got %d", hash)
	}

	emptySel := &text.Selection{}
	if hash := computeSelectionHash(emptySel); hash != 0 {
		t.Errorf("Empty selection hash should be 0, got %d", hash)
	}

	// Non-empty selection
	sel := &text.Selection{
		Anchor: text.Position{Line: 5, Col: 10},
		Head:   text.Position{Line: 10, Col: 20},
	}
	hash1 := computeSelectionHash(sel)
	if hash1 == 0 {
		t.Error("Non-empty selection should have non-zero hash")
	}

	// Same selection should produce same hash
	sel2 := &text.Selection{
		Anchor: text.Position{Line: 5, Col: 10},
		Head:   text.Position{Line: 10, Col: 20},
	}
	hash2 := computeSelectionHash(sel2)
	if hash1 != hash2 {
		t.Error("Same selection should produce same hash")
	}

	// Different selection should produce different hash (probably)
	sel3 := &text.Selection{
		Anchor: text.Position{Line: 1, Col: 0},
		Head:   text.Position{Line: 20, Col: 5},
	}
	hash3 := computeSelectionHash(sel3)
	if hash1 == hash3 {
		t.Error("Different selection should produce different hash")
	}
}

func TestNilViewportCache(t *testing.T) {
	theme := ui.NordTheme()
	var cache *ViewportCache = nil
	buf := text.NewBufferFromBytes([]byte("test"))
	v := Viewport{ScrollY: 0, Width: 80, Height: 24}

	// All operations should handle nil gracefully
	if cache.IsValid(buf, &v, nil, theme) {
		t.Error("Nil cache should not be valid")
	}

	cache.UpdateState(buf, &v, nil, theme) // Should not panic
	cache.InvalidateLine(0)                // Should not panic
	cache.InvalidateAll()                  // Should not panic
	cache.Resize(48)                       // Should not panic

	content, ok := cache.Get(0)
	if ok || content != "" {
		t.Error("Get on nil cache should return false")
	}

	cache.Set(0, 0, "content") // Should not panic
}
