// Code generated by teak - DO NOT EDIT
// This file is a work-in-progress (WIP) for Phase 3 optimization.
// ViewportCache will be integrated into the render loop to cache rendered lines
// and avoid redundant re-rendering when only cursor/selection changes.
//
// Status: Implementation complete, awaiting integration
// Expected improvement: Additional 2-5x render performance boost
// Issue: Currently unused - see viewport.go Render() methods

package editor

import (
	"teak/internal/text"
	"teak/internal/ui"
)

// ViewportCache caches rendered viewport content to avoid redundant re-rendering.
// It tracks buffer version, scroll position, dimensions, and selection state.
type ViewportCache struct {
	bufferVersion int
	scrollY       int
	width         int
	height        int
	selectionHash uint64
	themeVersion  uint64 // incremented on theme changes

	// Cached rendered lines indexed by viewport row (0 to height-1)
	lines []cachedLine
}

// cachedLine represents a single cached rendered line
type cachedLine struct {
	lineNum int    // absolute buffer line number
	content string // rendered content
	isValid bool   // whether this cache entry is valid
}

// NewViewportCache creates a new cache for the given viewport height.
func NewViewportCache(height int) *ViewportCache {
	return &ViewportCache{
		lines: make([]cachedLine, height),
	}
}

// IsValid checks if the cache is still valid for the given state.
// Returns false if buffer changed, scrolled, resized, selection changed, or theme changed.
func (vc *ViewportCache) IsValid(buf *text.Buffer, v *Viewport, sel *text.Selection, theme ui.Theme) bool {
	if vc == nil {
		return false
	}
	if vc.bufferVersion != buf.Version() {
		return false
	}
	if vc.scrollY != v.ScrollY || vc.width != v.Width || vc.height != v.Height {
		return false
	}

	// Check selection state
	selHash := computeSelectionHash(sel)
	if vc.selectionHash != selHash {
		return false
	}

	return true
}

// UpdateState updates the cache state to match current conditions.
func (vc *ViewportCache) UpdateState(buf *text.Buffer, v *Viewport, sel *text.Selection, theme ui.Theme) {
	if vc == nil {
		return
	}
	vc.bufferVersion = buf.Version()
	vc.scrollY = v.ScrollY
	vc.width = v.Width
	vc.height = v.Height
	vc.selectionHash = computeSelectionHash(sel)
}

// Get retrieves a cached line for the given viewport row.
func (vc *ViewportCache) Get(row int) (string, bool) {
	if vc == nil || row < 0 || row >= len(vc.lines) {
		return "", false
	}
	line := vc.lines[row]
	if !line.isValid {
		return "", false
	}
	return line.content, true
}

// Set caches a rendered line for the given viewport row.
func (vc *ViewportCache) Set(row int, lineNum int, content string) {
	if vc == nil || row < 0 || row >= len(vc.lines) {
		return
	}
	vc.lines[row] = cachedLine{
		lineNum: lineNum,
		content: content,
		isValid: true,
	}
}

// InvalidateLine marks a specific line as invalid.
func (vc *ViewportCache) InvalidateLine(lineNum int) {
	if vc == nil {
		return
	}
	for i := range vc.lines {
		if vc.lines[i].lineNum == lineNum {
			vc.lines[i].isValid = false
		}
	}
}

// InvalidateAll marks all cached lines as invalid.
func (vc *ViewportCache) InvalidateAll() {
	if vc == nil {
		return
	}
	for i := range vc.lines {
		vc.lines[i].isValid = false
	}
}

// Resize adjusts the cache size for a new viewport height.
// Preserves valid cached lines that fit within the new height.
func (vc *ViewportCache) Resize(height int) {
	if vc == nil {
		return
	}
	if height == len(vc.lines) {
		return
	}
	newLines := make([]cachedLine, height)
	copy(newLines, vc.lines)
	vc.lines = newLines
	vc.height = height
}

// computeSelectionHash creates a simple hash of the selection state.
func computeSelectionHash(sel *text.Selection) uint64 {
	if sel == nil || sel.IsEmpty() {
		return 0
	}
	start, end := sel.Ordered()
	// Simple hash: combine line numbers into 64-bit value
	return uint64(start.Line)<<32 | uint64(end.Line)
}
